### ISSUE TITLE
GlobalCaptureDevicePlugger does not seem to be included

### ISSUE THREAD

**Issue by vbence** [jitsi/fmj#3]
I am using the versions from maven central, and as I understand, `GlobalCaptureDevicePlugger.addCaptureDevices();` is the starting point for FMJ, but it does not seem to be included in the published jar file.

```
repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jitsi:fmj:1.0.0-jitsi'
```

**Comment by bgrozev** [comment]
This project isn't actively maintained anymore, we don't recommend using it.
